version: "3"

x-nginx-cmn: &nginx-cmn
  image: nginx:alpine
  networks:
    - app-network

services:
  app:
    build:
      context: ./app/.docker/app
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=chatapp
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  nginx-app:
    <<: *nginx-cmn
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
      - ./web/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  web:
    build:
      context: ./web/.docker/app
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    volumes:
      - ./web:/api
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    stdin_open: true
    tty: true

  nginx-web:
    <<: *nginx-cmn
    volumes:
      - ./web/.docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app
      - ./web/dist:/usr/share/nginx/html
    ports:
      - "90:90"
    depends_on:
      - web

  db:
    image: mysql:8.0.36
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
